# Generated by Django 5.1 on 2024-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_chatbot', '0002_alter_horarioaula_horario_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='calendarios/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
