# Generated by Django 5.1 on 2024-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_chatbot', '0003_calendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='ementa_materia',
            field=models.FileField(upload_to='ementa/'),
        ),
    ]
